[package]
name = "counter-sylvia"
version = "0.0.1"
edition = "2021"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "2", features = ["staking"] }
sylvia = "1"
serde = "1.0"
schemars = "0.8"
cosmwasm-schema = "2"
cw-storage-plus = "2"

[dev-dependencies]
sylvia = { version = "1.0.2", features = ["mt", "stargate"] }
cw-multi-test = { version = "2.1.0", features = ["cosmwasm_2_0", "staking"] }
